### ISSUE TITLE
Make at least one of safety observation & useful info mandatory to avoid blank entries

### ISSUE THREAD

**Issue by asanjeevrao** [covid-maps/covid-maps#59] opened 2020-04-01 00:36 UTC
Currently useful info is mandatory. Change this behaviour to make the form submittable as long as one of either safety observation & useful info is submitted.

**Comment by daviddhas** [comment] 2020-04-07 18:36
We've changed Validation is like (times OR useful info OR safety info)

**Comment by sampoorna** [comment] 2020-04-07 19:14
This can be closed out since it's a duplicate of the other one.

**Closed** 2020-04-09 06:13 UTC
Labels: P0, prioritized feature
